server:
  port: 4004
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: auth-service-route
            uri: http://auth-service:4006
            predicates:
              - Path=/auth/**
            filters:
                - StripPrefix=1
                - JwtValidation
          - id: patient-service-route
            uri: http://patient-service:4000
            predicates:
             - Path=/api/patients/**
            filters:
              - StripPrefix=1

